// Auto-generated by scripts/process-images.mjs
// Do not edit manually

export const characterImages = {
  "alisa-bosconovitch": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/alisa-bosconovitch"
  },
  "asuka-kazama": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/asuka-kazama"
  },
  "azucena": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/azucena"
  },
  "bryan-fury": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/bryan-fury"
  },
  "claudio-serafino": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/claudio-serafino"
  },
  "clive-rosfield": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/clive-rosfield"
  },
  "devil-jin": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/devil-jin"
  },
  "eddy-gordo": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/eddy-gordo"
  },
  "feng-wei": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/feng-wei"
  },
  "heihachi-mishima": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/heihachi-mishima"
  },
  "hwoarang": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/hwoarang"
  },
  "jack-8": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/jack-8"
  },
  "jin-kazama": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/jin-kazama"
  },
  "jun-kazama": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/jun-kazama"
  },
  "kazuya-mishima": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/kazuya-mishima"
  },
  "king": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/king"
  },
  "kuma": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/kuma"
  },
  "lars-alexandersson": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/lars-alexandersson"
  },
  "lee-chaolan": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/lee-chaolan"
  },
  "leo-kliesen": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/leo-kliesen"
  },
  "leroy-smith": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/leroy-smith"
  },
  "lidia-sobieska": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/lidia-sobieska"
  },
  "lili": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/lili"
  },
  "ling-xiaoyu": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/ling-xiaoyu"
  },
  "marshall-law": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/marshall-law"
  },
  "nina-williams": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/nina-williams"
  },
  "panda": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/panda"
  },
  "paul-phoenix": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/paul-phoenix"
  },
  "raven": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/raven"
  },
  "reina": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/reina"
  },
  "sergei-dragunov": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/sergei-dragunov"
  },
  "shaheen": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/shaheen"
  },
  "steve-fox": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/steve-fox"
  },
  "victor-chevalier": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/victor-chevalier"
  },
  "yoshimitsu": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/yoshimitsu"
  },
  "zafina": {
    "sizes": [
      128,
      256,
      512,
      1024
    ],
    "formats": [
      "webp",
      "png"
    ],
    "basePath": "/characters/zafina"
  }
} as const;

export type CharacterSlug = keyof typeof characterImages;

export function getCharacterImageSrc(slug: CharacterSlug, size: 128 | 256 | 512 | 1024 = 256): string {
  return `/characters/${slug}/${size}.webp`;
}

export function getCharacterImageSrcSet(slug: CharacterSlug): string {
  const sizes = [128, 256, 512, 1024] as const;
  return sizes
    .map(size => `/characters/${slug}/${size}.webp ${size}w`)
    .join(', ');
}
